import { writeFileSync, mkdirSync } from 'fs'
import { join } from 'path'
import { homedir } from 'os'
import { getAllQsos } from './db.js'

const LOG_DIR = join(homedir(), 'fac-shack', 'log')

function field(name, value) {
  if (value == null || value === '') return ''
  const s = String(value)
  return `<${name}:${s.length}>${s}`
}

export function exportAdif() {
  mkdirSync(LOG_DIR, { recursive: true })
  const now = new Date()
  const date = now.toISOString().slice(0, 10).replace(/-/g, '')
  const time = now.toISOString().slice(11, 19).replace(/:/g, '')
  const filepath = join(LOG_DIR, `facshack_export_${date}_${time}.adi`)

  const header = [
    'Generated by FAC Shack Dashboard',
    '<ADIF_VER:5>3.1.0',
    '<PROGRAMID:19>FAC Shack Dashboard',
    '<EOH>',
    ''
  ].join('\n')

  const records = getAllQsos().map(q => {
    const parts = [
      field('CALL',     q.callsign),
      field('FREQ',     q.freq),
      field('BAND',     q.band),
      field('MODE',     q.mode),
      field('RST_SENT', q.rst_sent),
      field('RST_RCVD', q.rst_rcvd),
      field('QSO_DATE', q.date_on?.replace(/-/g, '')),
      field('TIME_ON',  q.time_on),
      field('SRX',      q.skcc_nr),
      field('COMMENT',  q.notes),
    ].filter(Boolean).join(' ')
    return parts + ' <EOR>'
  }).join('\n')

  writeFileSync(filepath, header + records, 'utf8')
  return filepath
}
